name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:   # lets you trigger it manually too

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: PyRoS42/BrainTumorPipeline
          repo_type: model
          hf_token: ${{ secrets.HF_TOKEN }}
